---
- name: Deploy an app
  hosts: localhost
  become: false
  gather_facts: false
  vars:
     project: automation-ansible
  module_defaults:
    group/redhat.openshift.openshift:
      namespace: "{{ project }}"
      api_key: "{{ auth_results['openshift_auth']['api_key'] }}"
      host: https://api.ocp4.example.com:6443
      ca_cert: /etc/pki/tls/certs/ca-bundle.crt
    group/kubernetes.core.k8s:
      namespace: "{{ project }}"
      api_key: "{{ auth_results['openshift_auth']['api_key'] }}"
      host: https://api.ocp4.example.com:6443
      ca_cert: /etc/pki/tls/certs/ca-bundle.crt
