---
# tasks file for apache
- name:  Install httpd package
  ansible.builtin.yum:
    name: httpd
    state: latest

- name: Start and enable the httpd service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Open the ports
  ansible.posix.firewalld:
    service: http
    immediate: true
    permanent: true
    state: enabled

- name: Create the index file from template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html

