---
- name: Generate the hosts file
  hosts: all
  become: true
  tasks:
  - name: generate the /etc/myhosts file 
    ansible.builtin.template:
      src: hosts.j2
      dest: /etc/myhosts
    when: inventory_hostname in groups['dev']
...
