global:
  resolve_timeout: 5m
  smtp_smarthost: 192.168.50.254:25
  smtp_from: alerts@ocp4.example.com
  smtp_require_tls: false
receivers:
- name: Default
- name: email-notification
  email_configs:
    - to: ocp-admins@example.com
route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 1m
  routes:
  - match:
      alertname: Watchdog
    receiver: Default
  - match:
      severity: warning
    receiver: email-notification
